version: "3.9"

services:
  go-video-api:
    build: ./api
    container_name: go-video-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - big-bear-n8n_default

networks:
  big-bear-n8n_default:
    external: true
